/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.yeelight.rtt;

public class beacon_cmd_param_t {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected beacon_cmd_param_t(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(beacon_cmd_param_t obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        rtt_interfaceJNI.delete_beacon_cmd_param_t(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setMac_dev(String value) {
    rtt_interfaceJNI.beacon_cmd_param_t_mac_dev_set(swigCPtr, this, value);
  }

  public String getMac_dev() {
    return rtt_interfaceJNI.beacon_cmd_param_t_mac_dev_get(swigCPtr, this);
  }

  public void setMac_beacon(String value) {
    rtt_interfaceJNI.beacon_cmd_param_t_mac_beacon_set(swigCPtr, this, value);
  }

  public String getMac_beacon() {
    return rtt_interfaceJNI.beacon_cmd_param_t_mac_beacon_get(swigCPtr, this);
  }

  public void setKey(String value) {
    rtt_interfaceJNI.beacon_cmd_param_t_key_set(swigCPtr, this, value);
  }

  public String getKey() {
    return rtt_interfaceJNI.beacon_cmd_param_t_key_get(swigCPtr, this);
  }

  public beacon_cmd_param_t() {
    this(rtt_interfaceJNI.new_beacon_cmd_param_t(), true);
  }

}
