/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.yeelight.rtt;

public class rtt_interface implements rtt_interfaceConstants {
  public static SWIGTYPE_p_void rtt_connect(int timeout, SWIGTYPE_p_int err, int proto, String ip) {
    long cPtr = rtt_interfaceJNI.rtt_connect(timeout, SWIGTYPE_p_int.getCPtr(err), proto, ip);
    return (cPtr == 0) ? null : new SWIGTYPE_p_void(cPtr, false);
  }

  public static int rtt_discon(SWIGTYPE_p_void hdl) {
    return rtt_interfaceJNI.rtt_discon(SWIGTYPE_p_void.getCPtr(hdl));
  }

  public static int rtt_send(SWIGTYPE_p_void arg0, rt_cmd_t cmd) {
    return rtt_interfaceJNI.rtt_send(SWIGTYPE_p_void.getCPtr(arg0), rt_cmd_t.getCPtr(cmd), cmd);
  }

  public static int rtt_recv(SWIGTYPE_p_void arg0, rt_cmd_result_t arg1, rt_cmd_type_t arg2) {
    return rtt_interfaceJNI.rtt_recv(SWIGTYPE_p_void.getCPtr(arg0), rt_cmd_result_t.getCPtr(arg1), arg1, arg2.swigValue());
  }

  public static rt_status_t rtt_get_status(rt_cmd_result_t arg0, int idx) {
    long cPtr = rtt_interfaceJNI.rtt_get_status(rt_cmd_result_t.getCPtr(arg0), arg0, idx);
    return (cPtr == 0) ? null : new rt_status_t(cPtr, false);
  }

}
