/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.yeelight.rtt;

public class rt_cmd_t_body {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected rt_cmd_t_body(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(rt_cmd_t_body obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        rtt_interfaceJNI.delete_rt_cmd_t_body(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setCmd_param(rt_param_t value) {
    rtt_interfaceJNI.rt_cmd_t_body_cmd_param_set(swigCPtr, this, rt_param_t.getCPtr(value), value);
  }

  public rt_param_t getCmd_param() {
    long cPtr = rtt_interfaceJNI.rt_cmd_t_body_cmd_param_get(swigCPtr, this);
    return (cPtr == 0) ? null : new rt_param_t(cPtr, false);
  }

  public void setBeacon(beacon_cmd_param_t value) {
    rtt_interfaceJNI.rt_cmd_t_body_beacon_set(swigCPtr, this, beacon_cmd_param_t.getCPtr(value), value);
  }

  public beacon_cmd_param_t getBeacon() {
    long cPtr = rtt_interfaceJNI.rt_cmd_t_body_beacon_get(swigCPtr, this);
    return (cPtr == 0) ? null : new beacon_cmd_param_t(cPtr, false);
  }

  public void setMac(String value) {
    rtt_interfaceJNI.rt_cmd_t_body_mac_set(swigCPtr, this, value);
  }

  public String getMac() {
    return rtt_interfaceJNI.rt_cmd_t_body_mac_get(swigCPtr, this);
  }

  public rt_cmd_t_body() {
    this(rtt_interfaceJNI.new_rt_cmd_t_body(), true);
  }

}
