/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.yeelight.rtt;

public class rt_param_field_t {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected rt_param_field_t(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(rt_param_field_t obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        rtt_interfaceJNI.delete_rt_param_field_t(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setPrsnt(int value) {
    rtt_interfaceJNI.rt_param_field_t_prsnt_set(swigCPtr, this, value);
  }

  public int getPrsnt() {
    return rtt_interfaceJNI.rt_param_field_t_prsnt_get(swigCPtr, this);
  }

  public void setVal(int value) {
    rtt_interfaceJNI.rt_param_field_t_val_set(swigCPtr, this, value);
  }

  public int getVal() {
    return rtt_interfaceJNI.rt_param_field_t_val_get(swigCPtr, this);
  }

  public rt_param_field_t() {
    this(rtt_interfaceJNI.new_rt_param_field_t(), true);
  }

}
