#!/usr/bin/expect

set host [lindex $argv 0]
set user [lindex $argv 1]
set pass [lindex $argv 2]
set src  [lindex $argv 3]
set dest [lindex $argv 4]

spawn scp -oStrictHostKeyChecking=no -oUserKnownHostsFile=/dev/null $user@$host:$src $dest

while {1} {
    set timeout 3
    expect {
        eof {
            break
        }
        password {
            send "$pass\n"
        }
        timeout {
            break
        }
    }
}
