/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.8
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.yeelight.rtt;

public final class health_status_t {
  public final static health_status_t HEALTH_STATUS_UNKN = new health_status_t("HEALTH_STATUS_UNKN");
  public final static health_status_t HEALTH_STATUS_PASS = new health_status_t("HEALTH_STATUS_PASS");
  public final static health_status_t HEALTH_STATUS_FAIL = new health_status_t("HEALTH_STATUS_FAIL");

  public final int swigValue() {
    return swigValue;
  }

  public String toString() {
    return swigName;
  }

  public static health_status_t swigToEnum(int swigValue) {
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (int i = 0; i < swigValues.length; i++)
      if (swigValues[i].swigValue == swigValue)
        return swigValues[i];
    throw new IllegalArgumentException("No enum " + health_status_t.class + " with value " + swigValue);
  }

  private health_status_t(String swigName) {
    this.swigName = swigName;
    this.swigValue = swigNext++;
  }

  private health_status_t(String swigName, int swigValue) {
    this.swigName = swigName;
    this.swigValue = swigValue;
    swigNext = swigValue+1;
  }

  private health_status_t(String swigName, health_status_t swigEnum) {
    this.swigName = swigName;
    this.swigValue = swigEnum.swigValue;
    swigNext = this.swigValue+1;
  }

  private static health_status_t[] swigValues = { HEALTH_STATUS_UNKN, HEALTH_STATUS_PASS, HEALTH_STATUS_FAIL };
  private static int swigNext = 0;
  private final int swigValue;
  private final String swigName;
}

