/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.8
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.yeelight.rtt;

public final class rt_error_t {
  public final static rt_error_t RT_ERR_OK = new rt_error_t("RT_ERR_OK");
  public final static rt_error_t RT_ERR_BUSY = new rt_error_t("RT_ERR_BUSY");
  public final static rt_error_t RT_ERR_INVALID = new rt_error_t("RT_ERR_INVALID");
  public final static rt_error_t RT_ERR_CLEAR_DNS = new rt_error_t("RT_ERR_CLEAR_DNS");
  public final static rt_error_t RT_ERR_START_DNS = new rt_error_t("RT_ERR_START_DNS");
  public final static rt_error_t RT_ERR_START_HOSTAPD = new rt_error_t("RT_ERR_START_HOSTAPD");
  public final static rt_error_t RT_ERR_NOMEM = new rt_error_t("RT_ERR_NOMEM");
  public final static rt_error_t RT_ERR_FAILURE = new rt_error_t("RT_ERR_FAILURE");
  public final static rt_error_t RT_ERR_MAX = new rt_error_t("RT_ERR_MAX");
  public final static rt_error_t RT_ERR_INF = new rt_error_t("RT_ERR_INF", rtt_interfaceJNI.RT_ERR_INF_get());

  public final int swigValue() {
    return swigValue;
  }

  public String toString() {
    return swigName;
  }

  public static rt_error_t swigToEnum(int swigValue) {
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (int i = 0; i < swigValues.length; i++)
      if (swigValues[i].swigValue == swigValue)
        return swigValues[i];
    throw new IllegalArgumentException("No enum " + rt_error_t.class + " with value " + swigValue);
  }

  private rt_error_t(String swigName) {
    this.swigName = swigName;
    this.swigValue = swigNext++;
  }

  private rt_error_t(String swigName, int swigValue) {
    this.swigName = swigName;
    this.swigValue = swigValue;
    swigNext = swigValue+1;
  }

  private rt_error_t(String swigName, rt_error_t swigEnum) {
    this.swigName = swigName;
    this.swigValue = swigEnum.swigValue;
    swigNext = this.swigValue+1;
  }

  private static rt_error_t[] swigValues = { RT_ERR_OK, RT_ERR_BUSY, RT_ERR_INVALID, RT_ERR_CLEAR_DNS, RT_ERR_START_DNS, RT_ERR_START_HOSTAPD, RT_ERR_NOMEM, RT_ERR_FAILURE, RT_ERR_MAX, RT_ERR_INF };
  private static int swigNext = 0;
  private final int swigValue;
  private final String swigName;
}

