/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.8
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.yeelight.rtt;

public class rt_label_info_t {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected rt_label_info_t(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(rt_label_info_t obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        rtt_interfaceJNI.delete_rt_label_info_t(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setMac(String value) {
    rtt_interfaceJNI.rt_label_info_t_mac_set(swigCPtr, this, value);
  }

  public String getMac() {
    return rtt_interfaceJNI.rt_label_info_t_mac_get(swigCPtr, this);
  }

  public void setDid(String value) {
    rtt_interfaceJNI.rt_label_info_t_did_set(swigCPtr, this, value);
  }

  public String getDid() {
    return rtt_interfaceJNI.rt_label_info_t_did_get(swigCPtr, this);
  }

  public rt_label_info_t() {
    this(rtt_interfaceJNI.new_rt_label_info_t(), true);
  }

}
