/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.8
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.yeelight.rtt;

public interface rtt_interfaceConstants {
  public final static int MAX_TEST_DEV = rtt_interfaceJNI.MAX_TEST_DEV_get();
  public final static String rt_cmd_interface = rtt_interfaceJNI.rt_cmd_interface_get();
  public final static int RTT_PROTO_UNIX_SOCKET = rtt_interfaceJNI.RTT_PROTO_UNIX_SOCKET_get();
  public final static int RTT_PROTO_UDP = rtt_interfaceJNI.RTT_PROTO_UDP_get();
  public final static int UDP_PORT = rtt_interfaceJNI.UDP_PORT_get();
  public final static String STATE_ALLOC_IP = rtt_interfaceJNI.STATE_ALLOC_IP_get();
  public final static String STATE_IP_ALLOCED = rtt_interfaceJNI.STATE_IP_ALLOCED_get();
  public final static String STATE_PROBE = rtt_interfaceJNI.STATE_PROBE_get();
  public final static String STATE_HS = rtt_interfaceJNI.STATE_HS_get();
  public final static String STATE_DEV_CONN = rtt_interfaceJNI.STATE_DEV_CONN_get();
  public final static String STATE_PROBE_FAIL = rtt_interfaceJNI.STATE_PROBE_FAIL_get();
}
