#!/bin/bash

self=$(readlink -f "$0")
rtt_path=$(dirname "$self")
#rtt_path=$(dirname "$rtt_path")
self=$(basename "$self")
shlib_path=$rtt_path/misc

source "$shlib_path/common.sh"

action_name()
{
    case $1 in
        install)
            echo "安装"
        ;;
        prepare)
            echo "准备"
        ;;
        build)
            echo "生成"
        ;;
    esac
}

module_action()
{
    local module=""
    local action=$1
    local ret=0

    pushd "$rtt_path"
    local msg="执行$(action_name action)操作"
    dbg "$msg ..."

    for module in $(ls -d */ | grep -v misc | tr -d "/"); do
        pushd "$rtt_path/$module"

        local msg1="为模块$module执行$(action_name action)操作"

        dbg "$msg1 ..."
        ./"$action"
        checkrc $? "$msg1" || ret=1

        popd
    done

    popd

    checkrc $ret "$msg"

    return $ret
}

usage()
{
    echo "Usage: "
    echo "$self <prepare|build|install>"
}

sudoer_confirm()
{
    if ! grep $USER /etc/sudoers | grep -q NOPASSWD; then
        dbg "当前用户不能免密码执行sudo, 更新中..."
        sudo echo "$USER     ALL=(ALL) NOPASSWD:ALL" | sudo tee -a /etc/sudoers > /dev/null
        checkrc $? "加入免密码sudo权限"
    fi
}

action=$1

case "$action" in
    prepare|build|install)
        sudoer_confirm
        module_action $action
        ;;
    *)
        usage
        ;;
esac
